#!/usr/bin/python

import forecastio
from geopy.geocoders import Nominatim

# local imports
from apikey import key
import bcolors

# colors
blue = bcolors.Colors.BLUE
green = bcolors.Colors.GREEN
yellow = bcolors.Colors.YELLOW
red = bcolors.Colors.RED
end = bcolors.Colors.END

# user will input name of the city
user_input = input("")

# city related variables and calls
geolocator = Nominatim()
location = geolocator.geocode(user_input)
lat = location.latitude
lon = location.longitude

# forecast related variables and calls
forecast = forecastio.load_forecast(key, lat, lon, units='si')
byNow = forecast.currently()
summary = byNow.summary
temperature = int(byNow.temperature)
wind = byNow.windSpeed
clouds = byNow.cloudCover
pressure = int(byNow.pressure * 0.7500637554192) # mbar to mmHg


def fancy_icon(summ):

    summ = summ.lower()

    if "overcast" in summ or "cloudy" in summ:
        icon = blue + "☁ " + end
    elif "clear" in summ:
        icon = yellow + "☀ " + end
    elif "snow" in summ:
        icon = "❄"
    elif "drizzle" in summ or "rain" in summ:
        icon = blue + "☂" + end
    else:
        icon = ''
    return icon


def color_cloudcover(cloudcover):

    cloudcover *= 100  # get precents

    if cloudcover > 50:
        cloudcover = (blue + str(cloudcover) + end)
    else:
        cloudcover = (yellow + str(cloudcover) + end)
    return cloudcover

# def color_temperature(temp):

print(summary)
print(fancy_icon(summary))
print(color_cloudcover(clouds))